name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/1016726224165/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'admin-802@visszajaro-377613.iam.gserviceaccount.com'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/visszajaro:latest .

      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          region: 'region europe-west3'
          image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/visszajaro:latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service: visszajaro