name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/monolith:1.0.0 .

      - name: Deploy
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          region: 'europe-west3'
          image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/monolith:1.0.0'
          service: 'visszajaro'

      - name: Ready to Access
        run: curl ${{ steps.deploy.outputs.url }}